### ISSUE TITLE
"Error: `fsevents` unavailable" on jest --watch

### ISSUE THREAD

**Issue by cm-kazup0n** [cm-pliser-tdd-by-example/tdd-by-example-js#10]
```
> jest --watch

Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/sasaki.kazuhiro/src/github.com/cm-pliser-tdd-by-example/tdd-by-example-js/node_modules/sane/src/fsevents_watcher.js:41:11)
    at createWatcher (/Users/sasaki.kazuhiro/src/github.com/cm-pliser-tdd-by-example/tdd-by-example-js/node_modules/jest-haste-map/build/index.js:600:23)
    at Array.map (native)
    at HasteMap._watch (/Users/sasaki.kazuhiro/src/github.com/cm-pliser-tdd-by-example/tdd-by-example-js/node_modules/jest-haste-map/build/index.js:747:25)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/sasaki.kazuhiro/src/github.com/cm-pliser-tdd-by-example/tdd-by-example-js/node_modules/jest-haste-map/build/index.js:279:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)

npm ERR! Darwin 17.2.0
npm ERR! argv "/Users/sasaki.kazuhiro/.nodenv/versions/7.10.1/bin/node" "/Users/sasaki.kazuhiro/.nodenv/versions/7.10.1/bin/npm" "run" "watch"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tdd-by-example@1.0.0 watch: `jest --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tdd-by-example@1.0.0 watch script 'jest --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tdd-by-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tdd-by-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tdd-by-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sasaki.kazuhiro/.npm/_logs/2017-11-28T09_35_08_379Z-debug.log
```

**Comment by BuonOmo** [comment]
Did you find any solution yet? I'm facing the same issue...

**Comment by emyann** [comment]
@BuonOmo You might want to try this:
```
npm r -g watchman
brew install watchman
```
source: https://github.com/expo/expo/issues/854#issuecomment-343243804

**Comment by BuonOmo** [comment]
Thank you! The way I solved it was by reinstalling tons of stuff correctly and setting back python version to 2.7 (I think this was necessary for node-gyp)

**Comment by bit-dragon** [comment]
Thank you! 

Installing `watchman` from homebrew resolved the issue.

**Comment by johnelm** [comment]
Same here, installing watchman from homebrew resolved the issue.

I hadn't watchman in my global npm, so I didn't need to remove it from there.  ( It is present in node_modules as a dependency of sane, which is used by jest. )

**Comment by andyhuang12306** [comment]
reinstall watchman works for me too. thanks guys

**Comment by mikeperitz** [comment]
For those experiencing this problem in the future - it may not be necessary to install watchman.  First, check your version of node.  I was running 9.6.x and saw this error.  I upgraded to the latest version of node (10.11.0), and it fixed the issue.

**Comment by makkabi** [comment]
I just installed fsevents in my project: npm install fsevents

**Comment by Pixelatex** [comment]
@mikeperitz that fixed it for me, upgrading to 10.x.x instantly fixed it!

**Comment by riki95** [comment]
@makkabi fixed for me too, thanks

**Comment by ktoufighi** [comment]
Thanks guys and @BuonOmo that helped me as well. I was trying to run jest filename --watch and this helped me run the test with jest.

**Comment by Gshock1** [comment]
Hey there, for those who would not like to update all the dependencies, just make sure that you have the latest fsevents install on your node_modules.
I has the same problem and update only the fsevents library and it worked!

Hope it will help others.

**Comment by manojbhadane** [comment]
`killall node ` works for me

**Comment by sandra-arato** [comment]
Hi all,

I'm trying to work around the fsevents dependency on a Windows 7 machine. Even though it's supposed to be an 'optional dependency' - I can't run my tests as I get the following error:
```
Error: UNKNOWN: unknown error, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
```

I have tried to install watchman, which is in Beta on Windows, no luck with that either.
I started from a create-react-app, and tried to install it with yarn, npm, npm --no-optional. I'd really appreciate any tips or next steps. Thank you.

**Comment by maisonm** [comment]
Removing and then reinstalling watchman with homebrew worked perfectly. I was having this same issue. 

As @emyann posted: 
```

npm r -g watchman
brew install watchman
```

**Comment by propattern** [comment]
> @BuonOmo You might want to try this:
> 
> ```
> npm r -g watchman
> brew install watchman
> ```
> 
> source: [expo/expo#854 (comment)](https://github.com/expo/expo/issues/854#issuecomment-343243804)

Thank you.  After installing Big Sur, the tests started to fail and this solution fixed it for me.
